import{W,H,GROUND,LEVELS,overlap,layout,moveActor,segmentHit,makePlayer,makeEnemies,makeBoss,loadSave}from'./engine.js';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),overlay=document.querySelector('#overlay'),primary=document.querySelector('#primary'),secondary=document.querySelector('#secondary');
ctx.imageSmoothingEnabled=false;const keys=new Set();let mode='menu',level=0,p=makePlayer(),platforms=[],enemies=[],boss,shots=[],grenades=[],particles=[],pickups=[],hostages=[],camera=0,time=0,score=0,lives=3,checkpoint=90,banner=0,shake=0,audioOn=true,audioContext,save=loadSave(localStorage),toastTimer;
const $=s=>document.querySelector(s),rand=(a,b)=>a+Math.random()*(b-a),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function tone(freq,duration=.07,type='square',volume=.025){if(!audioOn)return;try{audioContext??=new AudioContext();if(audioContext.state==='suspended')audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.4),audioContext.currentTime+duration);g.gain.setValueAtTime(volume,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function persist(won=false){try{localStorage.setItem('impacto-rebelde-v1',JSON.stringify({level,score,won}));save={level,score,won};}catch{toast('Armazenamento indisponível: progresso nesta sessão.');}}
function screen(title,description,label,action,eyebrow='OPERAÇÃO AURORA'){keys.clear();overlay.hidden=false;$('#title').innerHTML=title;$('#description').textContent=description;$('#eyebrow').textContent=eyebrow;primary.textContent=label;primary.onclick=action;secondary.hidden=true;$('#hint').textContent='A/D mover · Espaço pular · J atirar · K granada · Esc pausa';}
function start(i=0,continuing=false){level=i;score=continuing?(save?.score||0):0;lives=3;loadLevel();}
function loadLevel(){p=makePlayer();platforms=layout(level);enemies=makeEnemies(level);boss=makeBoss(level);shots=[];grenades=[];particles=[];pickups=[];hostages=[];checkpoint=90;camera=0;banner=4;time=0;for(let x=1050;x<LEVELS[level].length-650;x+=1050){hostages.push({x,y:GROUND-40,w:24,h:40,saved:false});pickups.push({x:x+200,y:GROUND-24,w:24,h:24,type:x%2100===0?'health':'weapon',used:false});}mode='play';overlay.hidden=true;keys.clear();canvas.focus();persist();}
function burst(x,y,color,count=15){for(let i=0;i<count;i++)particles.push({x,y,vx:rand(-200,200),vy:rand(-220,100),life:rand(.2,.7),color,size:rand(2,6)});}
function damage(amount){if(p.inv>0||mode!=='play')return;p.hp-=amount;p.inv=1.15;shake=8;burst(p.x+12,p.y+20,'#ffa06a',8);tone(100,.14,'sawtooth');if(p.hp<=0){lives--;if(lives>0){p=makePlayer();p.x=checkpoint;p.inv=2.5;shots=shots.filter(s=>s.friendly);toast('Reagrupando no checkpoint.');}else{mode='over';screen('MISSÃO<br><em>INTERROMPIDA</em>','A resistência ainda precisa de você. Tente novamente a missão atual.','TENTAR NOVAMENTE',()=>{lives=3;loadLevel();});}}}
function hitEnemy(e,amount){if(e.dead)return;e.hp-=amount;e.flash=.09;if(e.hp<=0){e.dead=true;score+=e===boss?1500:100;burst(e.x+e.w/2,e.y+e.h/2,'#ffb75b',e===boss?65:18);tone(70,.25,'sawtooth',.05);if(e===boss){shake=16;shots=shots.filter(s=>s.friendly);pickups.push({x:e.x,y:GROUND-24,w:24,h:24,type:'health',used:false});toast('Chefão neutralizado. Avance até o ponto de extração!');}else if(Math.random()<.12)pickups.push({x:e.x,y:GROUND-24,w:24,h:24,type:'health',used:false});}}
function fire(){const up=keys.has('KeyW')||keys.has('ArrowUp'),crouch=keys.has('KeyS')||keys.has('ArrowDown');const x=p.x+14+(up?0:p.face*20),y=p.y+(up?4:crouch&&p.grounded?34:19);for(const spread of p.weapon===2?[-.16,0,.16]:[0]){shots.push({x,y,vx:up?Math.sin(spread)*800:p.face*800,vy:up?-800:Math.sin(spread)*800,life:1.5,friendly:true,power:p.weapon===1?2:1});}p.shot=p.weapon===1?.09:p.weapon===2?.26:.16;tone(p.weapon===2?150:220,.045);burst(x,y,'#ffe59a',3);}
function throwGrenade(){if(p.ammo<=0||p.grenade>0)return;p.ammo--;p.grenade=.55;grenades.push({x:p.x+14,y:p.y+12,w:8,h:8,vx:p.face*370,vy:-470,life:1.25,grounded:false});tone(500,.05);}
function complete(){score+=500+lives*100;mode=level===5?'win':'between';persist(level===5);if(level===5)screen('AURORA<br><em>LIBERTADA</em>',`Você encerrou a ocupação e devolveu a energia à cidade. Pontuação final: ${score.toLocaleString('pt-BR')}. Obrigado por jogar Impacto Rebelde!`,'JOGAR NOVAMENTE',()=>start(),'CAMPANHA CONCLUÍDA • DANIEL SOLIZ');else screen('MISSÃO<br><em>CONCLUÍDA</em>',`Próximo destino: ${LEVELS[level+1].name}. ${LEVELS[level+1].subtitle}. Pontuação: ${score}.`,'PRÓXIMA MISSÃO',()=>{level++;lives=Math.min(5,lives+1);loadLevel();});}
function pause(){if(mode==='play'){mode='pause';screen('OPERAÇÃO<br><em>EM PAUSA</em>','Respire. O campo de batalha espera por você.','VOLTAR AO JOGO',resume);}else if(mode==='pause')resume();}
function resume(){mode='play';overlay.hidden=true;keys.clear();canvas.focus();}
const gameKeys=['KeyA','KeyD','KeyW','KeyS','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyJ','KeyK','Escape','KeyP'];window.addEventListener('keydown',e=>{if(!gameKeys.includes(e.code))return;e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat)pause();return;}if(mode!=='play')return;if(e.code==='Space'&&!e.repeat)p.buffer=.14;if(e.code==='KeyK'&&!e.repeat)throwGrenade();keys.add(e.code);});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space'&&p.vy< -240)p.vy=-240;});window.addEventListener('blur',()=>{keys.clear();if(mode==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause();});
$('#audio').onclick=()=>{audioOn=!audioOn;$('#audio').textContent='ÁUDIO: '+(audioOn?'ON':'OFF');if(audioOn)tone(440);};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.stage').requestFullscreen();}catch{toast('Tela cheia indisponível neste navegador.');}};
function update(dt){time+=dt;if(mode!=='play'){for(const q of particles)q.life-=dt;return;}banner=Math.max(0,banner-dt);shake=Math.max(0,shake-30*dt);p.inv=Math.max(0,p.inv-dt);p.shot-=dt;p.grenade-=dt;p.buffer=Math.max(0,p.buffer-dt);p.weaponTime-=dt;if(p.weaponTime<=0)p.weapon=0;const left=keys.has('KeyA')||keys.has('ArrowLeft'),right=keys.has('KeyD')||keys.has('ArrowRight'),crouch=(keys.has('KeyS')||keys.has('ArrowDown'))&&p.grounded;p.vx=(Number(right)-Number(left))*(crouch?105:260);if(p.vx)p.face=Math.sign(p.vx);if(p.grounded)p.coyote=.1;else p.coyote=Math.max(0,p.coyote-dt);if(p.buffer>0&&p.coyote>0){p.vy=-580;p.grounded=false;p.coyote=0;p.buffer=0;tone(360,.09,'triangle');}moveActor(p,dt,platforms);p.x=clamp(p.x,0,LEVELS[level].length-p.w);if(p.y>H+100)damage(100);if(keys.has('KeyJ')&&p.shot<=0)fire();
const cp=Math.floor(p.x/1100)*1100+90;if(cp>checkpoint&&cp<LEVELS[level].length-650){checkpoint=cp;toast('Checkpoint alcançado • granadas reabastecidas');p.ammo=Math.max(p.ammo,5);}
for(const e of enemies){if(e.dead||Math.abs(e.x-p.x)>850)continue;e.flash=Math.max(0,(e.flash||0)-dt);if(e.type==='soldier'){e.x=e.origin+Math.sin(time*.9+e.phase)*48;e.y=GROUND-e.h;}else if(e.type==='drone'){e.y=GROUND-180+Math.sin(time*2+e.phase)*30;}else{e.w=38;e.h=34;e.y=GROUND-e.h;}e.cool-=dt;if(e.cool<=0&&Math.abs(p.x-e.x)<600){const dx=p.x+14-e.x-e.w/2,dy=p.y+22-e.y-15,d=Math.hypot(dx,dy);shots.push({x:e.x+e.w/2,y:e.y+15,vx:dx/Math.max(1,d)*(210+level*13),vy:dy/Math.max(1,d)*(210+level*13),life:4,friendly:false});e.cool=1.8+Math.random()*.8-level*.09;}if(overlap(p,e))damage(15);}
boss.active ||= p.x>boss.x-650;if(boss.active&&!boss.dead){boss.phase+=dt;boss.flash=Math.max(0,(boss.flash||0)-dt);boss.y=GROUND-boss.h+(level===3?Math.sin(boss.phase*1.7)*45-45:0);boss.cool-=dt;if(boss.cool<=0){const dx=p.x+14-(boss.x+20),dy=p.y+20-(boss.y+50),a=Math.atan2(dy,dx),count=boss.hp<boss.max*.5?5:3;for(let n=0;n<count;n++){const t=a+(n-(count-1)/2)*.16;shots.push({x:boss.x+20,y:boss.y+50,vx:Math.cos(t)*(220+level*12),vy:Math.sin(t)*(220+level*12),life:5,friendly:false});}boss.cool=Math.max(.65,1.5-level*.08);tone(90,.1,'triangle',.015);}if(overlap(p,boss))damage(25);}
for(const s of shots){const x=s.x,y=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.friendly){for(const e of [...enemies,boss])if(!e.dead&&(e!==boss||boss.active)&&segmentHit(x,y,s.x,s.y,e)){hitEnemy(e,s.power);s.life=0;break;}}else{const r=crouch?{x:p.x,y:p.y+22,w:p.w,h:26}:p;if(segmentHit(x,y,s.x,s.y,r)){damage(12);s.life=0;}}if(s.y>GROUND)s.life=0;}
shots=shots.filter(s=>s.life>0&&Math.abs(s.x-p.x)<1200&&s.y>-200);
for(const g of grenades){moveActor(g,dt,platforms);if(g.grounded)g.vx*=.94;g.life-=dt;if(g.life<=0){burst(g.x,g.y,'#ffbc58',45);shake=9;tone(60,.3,'sawtooth',.05);for(const e of [...enemies,boss])if(!e.dead&&(e!==boss||boss.active)&&Math.hypot(e.x+e.w/2-g.x,e.y+e.h/2-g.y)<180)hitEnemy(e,26);}}grenades=grenades.filter(g=>g.life>0);
for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=500*dt;q.life-=dt;}particles=particles.filter(q=>q.life>0).slice(-300);
for(const item of pickups)if(!item.used&&overlap(p,item)){item.used=true;if(item.type==='health'){p.hp=Math.min(100,p.hp+30);toast('Kit médico +30');}else{p.weapon=level%2+1;p.weaponTime=22;p.ammo+=3;toast(p.weapon===1?'METRALHADORA • 22 segundos':'ESCOPETA • 22 segundos');}tone(600,.15,'triangle');}
for(const h of hostages)if(!h.saved&&overlap(p,h)){h.saved=true;score+=300;p.ammo+=2;toast('Civil resgatado • +300 pontos • +2 granadas');tone(700,.18,'triangle');}
camera=clamp(p.x-W*.32,0,LEVELS[level].length-W);if(boss.dead&&p.x>LEVELS[level].length-100)complete();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function text(s,x,y,size=12,color='#f4efe1',align='left'){ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(s,x,y);ctx.textAlign='left';}
function background(){const l=LEVELS[level];rect(0,0,W,H,l.sky);const gradient=ctx.createLinearGradient(0,0,0,GROUND);gradient.addColorStop(0,l.sky);gradient.addColorStop(1,l.far);ctx.fillStyle=gradient;ctx.fillRect(0,0,W,GROUND);rect(738-camera*.03,65,65,65,level===4?'#d18157':'#e8ce9d');for(let layer=0;layer<2;layer++){const speed=layer?.38:.16,col=layer?l.near:l.far;for(let n=-1;n<10;n++){const x=n*180-(camera*speed%180),height=80+((n+11)*47%130);if(level===1){rect(x+65,GROUND-height,15,height,col);ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(x,GROUND-height+50);ctx.lineTo(x+75,GROUND-height-80);ctx.lineTo(x+155,GROUND-height+50);ctx.fill();}else if(level===3){ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(x-80,GROUND);ctx.lineTo(x+70,GROUND-height-70);ctx.lineTo(x+240,GROUND);ctx.fill();if(layer===0){ctx.fillStyle='#a1b6be';ctx.beginPath();ctx.moveTo(x+36,GROUND-height-15);ctx.lineTo(x+70,GROUND-height-70);ctx.lineTo(x+105,GROUND-height-15);ctx.fill();}}else{rect(x,GROUND-height,95,height,col);rect(x+20,GROUND-height-25,12,25,col);for(let j=0;j<4;j++)rect(x+12+j*18,GROUND-height+18,7,10,layer?'#ffffff0b':'#e2b96c20');}}}rect(0,GROUND,W,H-GROUND,l.ground);rect(0,GROUND,W,7,l.accent);for(let n=0;n<45;n++)rect((n*39-camera%39),GROUND+17+(n*13%65),15,3,'#00000025');}
function soldier(x,y,face,friendly=false,walk=0,crouch=false){const body=friendly?'#e5ab55':'#809884',dark=friendly?'#274e65':'#344e43';const yy=y+(crouch?20:0);if(crouch){rect(x+2,yy+18,25,10,dark);rect(x+2,yy+27,29,6,'#1a2832');}else{const step=Math.sin(walk)*5;rect(x+3,yy+28,8,14+step,dark);rect(x+17,yy+28,8,14-step,dark);rect(x,yy+41+step,12,5,'#192832');rect(x+17,yy+41-step,13,5,'#192832');}rect(x+4,yy+13,22,crouch?10:18,body);rect(x+8,yy+3,15,12,'#ecc39c');rect(x+4,yy,23,6,dark);rect(x+19,yy+6,5,4,'#132d3b');rect(x+7,yy+17,12,4,'#f2c8a1');const up=friendly&&(keys.has('KeyW')||keys.has('ArrowUp'));if(up){rect(x+12,yy-12,6,30,'#182831');rect(x+10,yy-11,10,5,'#748992');}else{rect(face>0?x+15:x-17,yy+18,32,6,'#182831');rect(face>0?x+34:x-17,yy+17,11,3,'#8195a0');}if(friendly){rect(x+4,yy+13,5,14,'#f6cd77');rect(x-3,yy+13,7,16,'#385768');}}
function drawBoss(){if(boss.dead)return;const b=boss,x=b.x,y=b.y;const colors=['#8e9873','#78895b','#987a69','#92b6bd','#ae7052','#688eaa'];rect(x-4,y+b.h-27,b.w+8,27,'#17252e');for(let n=0;n<6;n++){ctx.fillStyle='#687580';ctx.beginPath();ctx.arc(x+10+n*25,y+b.h-13,10,0,Math.PI*2);ctx.fill();rect(x+6+n*25,y+b.h-16,8,5,'#1c2c34');}rect(x+6,y+36,b.w-12,b.h-60,b.flash>0?'#fff0c3':colors[level]);rect(x+26,y+16,95,35,colors[level]);rect(x-40,y+39,75,14,'#293c48');rect(x-45,y+35,12,22,'#7e9094');rect(x+43,y+4,51,18,'#293d48');rect(x+49,y+8,35,6,level===5?'#78eef0':'#ffca73');rect(x+15,y+59,b.w-32,5,'#0003');rect(x+60,y+65,25,20,'#364652');if(b.active){rect(245,78,470,26,'#0b1523dd');rect(250,98,460,4,'#ffffff20');rect(250,98,460*Math.max(0,b.hp/b.max),4,'#ffae62');text(LEVELS[level].boss.toUpperCase(),480,91,10,'#f5bc74','center');}}
function draw(){ctx.save();if(shake)ctx.translate(rand(-shake,shake),rand(-shake/2,shake/2));background();ctx.save();ctx.translate(-Math.round(camera),0);const l=LEVELS[level];for(const platform of platforms.slice(1)){rect(platform.x,platform.y,platform.w,platform.h,'#344d58');rect(platform.x,platform.y,platform.w,4,l.accent);rect(platform.x+15,platform.y+18,8,GROUND-platform.y-18,'#233944');rect(platform.x+platform.w-22,platform.y+18,8,GROUND-platform.y-18,'#233944');}for(let x=320;x<l.length-650;x+=740){rect(x,GROUND-29,42,29,'#776d51');rect(x+3,GROUND-26,36,3,'#baa372');rect(x+18,GROUND-25,4,22,'#4e4b37');}for(const h of hostages)if(!h.saved){soldier(h.x,h.y,1,false,0,true);text('SOS',h.x+12,h.y-10,11,'#ffd77d','center');}for(const e of enemies)if(!e.dead){if(e.type==='soldier')soldier(e.x,e.y,p.x>e.x?1:-1,false,time*8);else if(e.type==='drone'){rect(e.x-12,e.y+6,55,7,'#9aafae');rect(e.x,e.y,28,20,e.flash?'#fff':'#4a6a77');rect(e.x+10,e.y+18,7,10,'#ffbd67');rect(e.x-16,e.y+4,12,3,'#263942');rect(e.x+42,e.y+4,12,3,'#263942');}else{rect(e.x,e.y+12,38,22,'#526b68');rect(e.x+5,e.y,28,18,'#8e9b80');rect(e.x-13,e.y+4,24,6,'#293d45');}if(e.flash)rect(e.x+5,e.y,16,4,'#ffdc9d');}drawBoss();for(const i of pickups)if(!i.used){const y=i.y+Math.sin(time*4)*3;rect(i.x-2,y-2,28,28,'#142d3a');rect(i.x,y,24,24,i.type==='health'?'#8fc5b0':'#efb766');text(i.type==='health'?'+':'W',i.x+12,y+17,18,'#162d38','center');}for(const g of grenades){rect(g.x,g.y,8,10,'#a9bd77');rect(g.x+2,g.y-3,4,4,'#fff0ac');}for(const s of shots){rect(s.x-(s.friendly?6:3),s.y-2,s.friendly?14:7,4,s.friendly?'#ffe4a1':'#ff7d62');}if(p.inv<=0||Math.floor(time*18)%2===0)soldier(p.x,p.y,p.face,true,p.vx?time*13:0,(keys.has('KeyS')||keys.has('ArrowDown'))&&p.grounded);for(const q of particles)rect(q.x,q.y,q.size,q.size,q.color);const exit=l.length-90;rect(exit,GROUND-125,6,125,'#c4d5d9');rect(exit+6,GROUND-125,55,35,boss.dead?'#9fdaaf':'#ad7770');text(boss.dead?'SAÍDA':'BLOQUEADO',exit-15,GROUND-145,11,boss.dead?'#c4eccb':'#f1ba97');ctx.restore();ctx.restore();
rect(0,0,W,61,'#0a1724ed');text('IR',20,34,24,'#ffbd66');text('AGENTE • RESISTÊNCIA',67,21,10,'#98aebb');rect(67,29,160,10,'#ffffff15');rect(67,29,160*Math.max(0,p.hp/100),10,p.hp<30?'#ef7d68':'#a6d3a6');text(`${Math.max(0,p.hp)} HP`,237,39,11);text(`VIDAS ${lives}`,325,24,12);text(`GRANADAS ${p.ammo}`,325,43,10,'#edc386');text(`MISSÃO ${level+1}/6`,500,24,12,'#ffbf6b');text(LEVELS[level].name.toUpperCase(),500,43,10,'#b7c9d4');text(String(score).padStart(7,'0'),W-20,32,20,'#f2ead4','right');text(p.weapon===0?'FUZIL':`${p.weapon===1?'METRALHADORA':'ESCOPETA'} ${Math.ceil(Math.max(0,p.weaponTime))}s`,22,H-18,12,'#ffcf85');rect(W-220,H-28,195,5,'#ffffff20');rect(W-220,H-28,195*clamp(p.x/LEVELS[level].length,0,1),5,'#e8ba77');if(banner>0&&mode==='play'){rect(250,135,460,64,'#0d1d2ae8');text(`MISSÃO ${level+1} — ${LEVELS[level].name.toUpperCase()}`,480,162,18,'#ffcb82','center');text(LEVELS[level].subtitle,480,184,11,'#d2dee0','center');}}
platforms=layout(0);enemies=makeEnemies(0);boss=makeBoss(0);camera=350;p.x=450;primary.onclick=()=>start();if(save){secondary.hidden=false;secondary.onclick=()=>start(save.won?0:save.level,true);}
let last=0,accumulator=0;function frame(now){const delta=Math.min(.1,(now-last)/1000||0);last=now;accumulator+=delta;while(accumulator>=1/120){update(1/120);accumulator-=1/120;}draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('#offline').textContent='PRONTO PARA JOGAR OFFLINE';}).catch(()=>{$('#offline').textContent='MODO ONLINE • CACHE INDISPONÍVEL';});}else $('#offline').textContent='NAVEGADOR SEM CACHE OFFLINE';
