import{test}from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import fs from'node:fs';import*as engine from'../engine.js';
async function harness(){const elements=new Map(),handlers={},ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]??(()=>{})});function el(s){if(!elements.has(s))elements.set(s,{hidden:s==='#secondary',textContent:'',innerHTML:'',classList:{add(){},remove(){}},focus(){},getContext:()=>ctx});return elements.get(s);}const storage=new Map();const sandbox={console,Math,Set,Number,JSON,setTimeout:()=>0,clearTimeout(){},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},document:{querySelector:el,addEventListener:(k,v)=>handlers[k]=v},navigator:{},window:{addEventListener:(k,v)=>handlers[k]=v},requestAnimationFrame(){}};const context=vm.createContext(sandbox);const mod=new vm.SourceTextModule(fs.readFileSync(new URL('../game.js',import.meta.url),'utf8')+'\nexport const testing={state:()=>({mode,level,p,shots,boss,score,lives}),step:n=>{for(let i=0;i<n;i++)update(1/120);draw();},key:(k,v)=>v?keys.add(k):keys.delete(k),immune:()=>p.inv=10000,start,damage};',{context});const em=new vm.SyntheticModule(Object.keys(engine),function(){for(const[k,v]of Object.entries(engine))this.setExport(k,v)},{context});await mod.link(()=>em);await mod.evaluate();return{t:mod.namespace.testing,bind:mod.namespace.bindTouchButton,el,handlers,storage};}
test('keyboard jump, fire, grenade, pause and focus handling',async()=>{const{t,el,handlers}=await harness();el('#primary').onclick();assert.equal(t.state().mode,'play');const key=(code,repeat=false)=>handlers.keydown({code,repeat,preventDefault(){}});key('Space');t.step(20);assert.ok(t.state().p.y<402);handlers.keyup({code:'Space'});t.step(200);assert.equal(t.state().p.y,402);key('KeyJ');t.step(3);assert.ok(t.state().shots.length>0);handlers.keyup({code:'KeyJ'});key('KeyK');assert.equal(t.state().p.ammo,7);key('Escape');assert.equal(t.state().mode,'pause');const x=t.state().p.x;t.step(120);assert.equal(t.state().p.x,x);el('#primary').onclick();assert.equal(t.state().mode,'play');handlers.blur();assert.equal(t.state().mode,'pause');});
test('nine actual boss battles reach campaign ending with controlled invulnerability',async()=>{const{t,el}=await harness();t.start();for(let stage=0;stage<engine.LEVELS.length;stage++){t.immune();t.key('KeyD',true);t.key('KeyJ',true);let s;for(let n=0;n<200;n++){s=t.state();if(!s.boss.dead&&s.p.x>s.boss.x-220)t.key('KeyD',false);if(s.boss.dead)t.key('KeyD',true);t.step(120);s=t.state();if(s.mode==='between'||s.mode==='win')break;}assert.equal(s.level,stage);assert.equal(s.mode,stage===engine.LEVELS.length-1?'win':'between');assert.ok(s.boss.dead);if(stage<engine.LEVELS.length-1)el('#primary').onclick();}assert.ok(t.state().score>9000);});
test('death consumes lives, respawns then allows retry',async()=>{const{t,el}=await harness();t.start();for(let i=0;i<3;i++){t.state().p.inv=0;t.damage(100);assert.equal(t.state().lives,2-i);}assert.equal(t.state().mode,'over');el('#primary').onclick();assert.equal(t.state().mode,'play');assert.equal(t.state().lives,3);assert.equal(t.state().p.hp,100);});
test('all offline shell resources exist and no remote resources required',()=>{const source=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');for(const file of['index.html','style.css','game.js','engine.js','icon.svg','manifest.webmanifest']){assert.ok(source.includes(file));assert.ok(fs.existsSync(new URL('../'+file,import.meta.url)));}assert.equal(fs.readFileSync(new URL('../style.css',import.meta.url),'utf8').includes('@import'),false);});

test('touch supports simultaneous movement, shooting, jump, grenade and cancellation',async()=>{
 const {t,bind,handlers,el}=await harness();t.start();
 function button(key){const events={},b={dataset:{key},classList:{add(){},remove(){}},setPointerCapture(){},addEventListener:(name,fn)=>events[name]=fn};bind(b);return{down:id=>events.pointerdown({pointerId:id,pointerType:'touch',preventDefault(){}}),up:id=>events.pointerup({pointerId:id}),cancel:id=>events.pointercancel({pointerId:id})};}
 const right=button('KeyD'),fire=button('KeyJ'),jump=button('Space'),grenade=button('KeyK');
 right.down(1);fire.down(2);t.step(10);assert.ok(t.state().p.x>90);assert.ok(t.state().shots.length>0);
 jump.down(3);t.step(10);assert.ok(t.state().p.vy<0);jump.up(3);assert.ok(t.state().p.vy>=-240);
 grenade.down(4);assert.equal(t.state().p.ammo,7);grenade.down(4);assert.equal(t.state().p.ammo,7);grenade.up(4);
 right.down(5);right.up(1);t.step(1);assert.ok(t.state().p.vx>0);right.cancel(5);fire.cancel(2);t.step(1);assert.equal(t.state().p.vx,0);
 handlers.keydown({code:'KeyD',repeat:false,preventDefault(){}});right.down(6);right.up(6);t.step(1);assert.ok(t.state().p.vx>0);handlers.keyup({code:'KeyD'});
 right.down(7);handlers.blur();assert.equal(t.state().mode,'pause');el('#primary').onclick();t.step(1);assert.equal(t.state().p.vx,0);
});
